export const zones = [
  { zone_name: "zone_A", total_stay_time_seconds: 1800, score: 18 },
  { zone_name: "zone_B", total_stay_time_seconds: 1740, score: 15 },
  { zone_name: "zone_C", total_stay_time_seconds: 690, score: 7 },
  { zone_name: "zone_D", total_stay_time_seconds: 1110, score: 10 },
  { zone_name: "zone_E", total_stay_time_seconds: 420, score: 5 },
  { zone_name: "zone_F", total_stay_time_seconds: 680, score: 3 },
  { zone_name: "zone_G", total_stay_time_seconds: 990, score: 6 },
];

export const customerData = {
  month: 5,
  day: 19,
  customer_tracking_records: [
    {
      customer_id: 1,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 2,
      zone_entrance: 0,
      zone_checkout: 210,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 3,
      zone_entrance: 120,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 4,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 5,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 6,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 7,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 8,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 9,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
    {
      customer_id: 10,
      zone_entrance: 180,
      zone_checkout: 0,
      zone_A: 300,
      zone_B: 0,
      zone_C: 20,
      zone_D: 100,
      zone_E: 140,
      zone_F: 215,
      zone_G: 30,
      purchase_state: false,
      score: 12,
    },
  ],
};
